inlife/nexrender

- api/models/project.js
setStateAndSave had too many arguments and failed to set the state variable, causing projects to be queued and rendered in a loop.
> Fix for issue #19

- renderer/tasks/download.js
- test/renderer/tasks/download.js
This PR fix an error when assigning a local path to asset src.
> Fixed loading local file bug

- package.json
- renderer/tasks/rename.js
- test/renderer/tasks/rename.js
This PR fix an error on rename asset src with query.
For example:
http://example.com/proj.aep?q=test
> Fix error on renaming asset src with query

- cli.js
- renderer/index.js
- renderer/tasks/render.js
Added `log` parameter, see https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html `–log log_file_path`
> Added log parameter to render

- renderer/index.js
- renderer/tasks/render.js
> fix typing error

- packages/nexrender-api/src/index.js
- packages/nexrender-api/src/job.js
> Allow for changing api polling with settings param

- packages/nexrender-core/src/tasks/render.js
Correctly calulate percentage when startFrame is not the first frame
> Correctly calculate percentage

- packages/nexrender-core/src/assets/nexrender.jsx
this project is awesome.
i fixed a bug with operator precedence in template jsx.
please check it out.
> Fixed condition of detecting composition class in jsx.

- README.md
> Added two bit circus to 'proud users'

- packages/nexrender-action-encode/index.js
A small update to settings to allow video to be played in Quick Time
> Update preset settings for MP4 to allow QT playback

- packages/nexrender-action-upload/index.js
- packages/nexrender-action-upload/package.json
> Fix missing reference to requireg

- packages/nexrender-action-upload/index.js
- packages/nexrender-action-upload/package.json
- packages/nexrender-provider-ftp/package.json
- packages/nexrender-provider-ftp/src/index.js
Added FTP Provider with download and upload functions
> Added FTP Provider and implemented in action-upload

- packages/nexrender-core/src/tasks/download.js
This fixes #194
(Had to rebase in order to make it more understandable)
> Fixed: settings undefined in core/src/download.js

- packages/nexrender-core/src/tasks/script.js
* Added new wrap data variant for attributes
* strategy is "freely mix attributes and properties"
* using eval for expressions
> Manipulating Javascript attributes

- README.md
- packages/nexrender-core/src/helpers/path.js
- packages/nexrender-core/src/tasks/download.js
- packages/nexrender-core/src/tasks/render.js
> Allow the use of environment variables in file:// paths

- packages/nexrender-provider-ftp/src/index.js
1. Exception handling in readfile, FTP connect, FTP put
2. Add comments
> Improve FTP Provider: Exception handling and comments

- README.md
I've noticed a small typo on README.md and decided to give my 2 cents, this is such a great project.
> Fix a small typo on README.md

- packages/nexrender-core/src/tasks/render.js
fix[issue#236]:on windows platform, wrong way to use push , so that spwan cant pass correct params to aerender.exe (can only pass the 1st param)
> fix[issue#236]

- README.md
Current link doesn't work - this PR updates the Lerna link :)
> Fix Lerna Link in Readme

- packages/nexrender-cli/src/bin.js
> feat:  invalid parameter

- packages/nexrender-core/src/assets/nexrender.jsx
`nexrender.selectLayersByType` invokes callback for each layer of a certain type.
needed to manipulate the Font Family of every text layer in my compositions.
> added selectLayersByType method

- packages/nexrender-action-encode/index.js
> @nexrender/action-encode Improve Error handling

- README.md
Thank you all for this awesome piece of software!
> Added my channel to the user list in the readme

- packages/nexrender-server/src/routes/jobs-create.js
- packages/nexrender-server/src/routes/jobs-update.js
https://github.com/inlife/nexrender/issues/402
> set default size for upload to overwrite mirco default

- packages/nexrender-core/src/tasks/download.js
changing error from `url` (a dependancy module) to `src`
> Update download.js - changing error from `url` (a dependancy module) to `src`

- packages/nexrender-server/README.md
fixing example typo post > port
> Update README.md - fixing example typo post > port

- packages/nexrender-action-upload/index.js
Resolves #415
Haven't test it out fully but existing functionality should work as before.
> Enable globally installed custom upload action

- packages/nexrender-server/src/helpers/database.js
Add a test on database.js content before parsing JSON to prevent error with existing but empty file.
> @nexrender/server Add test on database content

- packages/nexrender-cli/src/bin.js
- packages/nexrender-core/src/tasks/render.js
- packages/nexrender-worker/src/bin.js
>  Forward all parameters to aerender

- packages/nexrender-types/job.js
Solve[ #issue482](https://github.com/inlife/nexrender/issues/482)
> Add Custom UID to Job

- packages/nexrender-server/src/routes/jobs-remove.js
solve issue https://github.com/inlife/nexrender/issues/488
> add a body to the removeJob response

- packages/nexrender-action-encode/index.js
Adds support for arrays in ffmpeg parameters.
> support repeated ffmpeg parameters in action-encode

- packages/nexrender-provider-s3/src/index.js
Resolves  #493
Add a new key to assets download and rendered video upload `params` object called `endpoint` where one can set a custom endpoint for a S3 compatible storage.
Download assets:
```json
"assets": [
{
"src": "s3://eu-central-001.backblazeb2.com/background.jpg",
"type": "image",
"layerName": "background.png",
"params": {
"endpoint": "https://s3.eu-central-001.backblazeb2.com"
}
}
]
```
Upload assets (with `nexrender-action-upload`):
```json
{
"module": "@nexrender/action-upload",
"input": "output.mp4",
"provider": "s3",
"params": {
"endpoint": "https://s3.eu-central-001.backblazeb2.com",
"bucket": "name-of-your-bucket",
"key": "folder/output.mp4",
"acl": "public-read"
}
}
```
I've done basic tests with Backblaze B2 and I think Digital Ocean Spaces should work as well but I …
> Enable Use of Custom S3 Endpoints

- packages/nexrender-provider-s3/src/index.js
Noticed a typo that threw an error that prevents the upload action from working. Sorry about that.
I'm still working assets download into my workflow and if I found a bug I'll file another PR.
> Fix bug where S3 custom endpoint isn't working

- packages/nexrender-api/src/job.js
> Add resumeJob method to nexrender-api

- packages/nexrender-worker/src/index.js
> Fix worker stopping on error when unable to connect to server

- README.md
Fixed the link to my Youtube channel in the "Customers" section in the main Readme.md
> Fixed a Customer Link

- packages/nexrender-provider-s3/readme.md
- packages/nexrender-provider-s3/src/index.js
> added support param content type on  Action Upload Provider-S3

- packages/nexrender-core/src/helpers/autofind.js
Related to: https://github.com/inlife/nexrender/issues/647
> Add After Effects 2022 to autofind helper function

- packages/nexrender-core/src/tasks/render.js
Hi @inlife!
Nexrender is a great lib, we love to use it in out video automation projects.
I've been having some trouble after updating it to AE 2022 due to the autofind helper that I've fixed in this PR: https://github.com/inlife/nexrender/pull/651
But this behavior also occurred to us: it seems on windows workers the outputFile is always being forced as `.mov`.
I don't know if this would be the best workaround, but it worked for our case.
Let me know your thoughts on it.
> Adapt render task to look for .mov file too

- packages/nexrender-core/src/tasks/actions.js
Fix bugs found by @pilwon in #672
> Fix bug relating to optional actions field and error handling

- packages/nexrender-api/src/job.js
Add a method to the api that allows subscribing to events of a job using the uid
> Subscribe to events by uid

- README.md
- packages/nexrender-core/src/assets/nexrender.jsx
- packages/nexrender-core/src/tasks/script.js
added bypass if couldn't find any layers
> added bypass if couldn't find any layers

- packages/nexrender-core/src/index.js
- packages/nexrender-core/src/tasks/setup.js
- packages/nexrender-provider-sftp/src/index.js
- packages/nexrender-worker/src/index.js
Fix for issue #814 
Fixed two linting errors
> Fix for issue #814

- packages/nexrender-core/src/tasks/render.js
Hi @inlife 
I made a Network Rendering setup using Worker (7 Worker), API and mini cron job to re-queue an error job.
It works fine.
But when i'm starting the job with large data ( >5000 jobs ), They stuck on `rendering job...` for a certain time. I need to limit rendering process so i can re-queue the job when error/failed.
So i made this little changes,
> an optional setting that limit render execution to prevent stuck forever.
Are this changes acceptable?
> Add maximum render execution time

- packages/nexrender-core/src/assets/commandLineRenderer-2022.jsx
> Fix for #897

- README.md
Created a package that would call a WebHook URL once the project has been completed.
I've added the package in the ReadMe.
> Added WebHook PostRender action to External Packages List

- README.md
Added Danish Broadcaster TV2 that I implement rendering systems for using nexrender.
> Update README.md with another customer

- packages/nexrender-core/src/assets/nexrender.jsx
the function removes the old footage from the ae project
> Improved nexrender.replaceFootage function:

- packages/nexrender-server/README.md
Update server > README.md file.
Add an explanation to the README.md file about the callback function added to the listen function
> A small doc update:

- packages/nexrender-server/src/index.js
- packages/nexrender-server/src/routes/jobs-pickup.js
- packages/nexrender-worker/readme.md
The name on worker can be used as an executor name on picked job(s) as well
> The name on worker can be used as an executor name on picked job(s) as well

- packages/nexrender-core/src/tasks/download.js
noticed that the download timeout doesn't work while downloading assets. Some links may not return any response and job doesn't continue processing but just gets stuck. Added a timeout for the fetch method when downloading assets, this solved the problem
> add timeout for fetch assets
