- renderer/tasks/patch.js
Error message:
for (let expr of expressions) {
^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
addressed by adding an additional null check.
> List of expressions could be null resulting in a crash

- renderer/tasks/patch.js
Paths with a '+' sign in the directory name wouldn't get parsed correctly and resulted in a new regex match. For example the following expression wouldn't be replaced correctly: "$.evalFile('D:\\Something\\Project\Whatever\\Pilot+Project\\Pilot Project\\scripts\\name.js'); getName();"
> Updated regular expression to match paths that include '+' character

- package.json
The previous version of the dependency is unsafe, more info:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809252
Tested with `nsp`: https://github.com/nodesecurity/nsp
> changed version of `cli` dependency to more secure

- packages/nexrender-action-encode/index.js
This postrender action was failing
```
"actions": {
"prerender": [],
"postrender": [
{
"module": "@nexrender/action-encode",
"output": "/Users/egradman/dev/vr_loop/output/simurai.mp4",
"preset": "mp4",
"params": {
"-vcodec": "libx264",
"-r": 25,
"-pix_fmt": "yuv420p"
}
}
]
}
```
because I was introducing a _new_ key (`pix_fmt`) which wasn't in the original argument list.   In `ffmpeg` the output filename argument always has to come last, so I changed the Object.assign to always add the output filename argument after all the params.
(`pix_fmt` is required on MacOS X for Quicktime to recognize files encoded with libx264)
> fixed ffmpeg commandline argument ordering

- packages/nexrender-worker/src/index.js
I find it very useful when I can change all settings using the setting object. It might be easier and more intuitive  than setting the polling delay through env variable
> Allow setting polling delay through settings variable

- packages/nexrender-server/src/helpers/database.js
- packages/nexrender-server/src/routes/jobs-create.js
- packages/nexrender-server/src/routes/jobs-update.js
- packages/nexrender-worker/src/index.js
1. I moved setting createdAt and updatedAt to database. I believe its clear that way because its teh db responsibility to track when something was created/updated
2. When there are multiple queued jobs they are selected by workers randomly. That helps to spread out a load between them
3. Entry in the database can be only updated when you are updating most recent version of it
4. When worker tries to start job started by someone self it abandons that job and queries server for something else
Resolves my issues #109  and #103
> Prevent conflicts with concurrent requests form multiple workers

- packages/nexrender-core/src/assets/nexrender.jsx
When callback changes ```app.project.items.length``` the script might get stuck in infinite loop.
> Fix infinite loop

- packages/nexrender-action-upload/index.js
- packages/nexrender-action-upload/package.json
- packages/nexrender-action-upload/readme.md
- packages/nexrender-provider-s3/package.json
- packages/nexrender-provider-s3/src/index.js
This PR implements a post-render action for uploading to an S3 bucket.
Upload video to an external storage provider ie. Amazon S3.
```
npm i @nexrender/action-upload -g
```
When creating your render job provide this module as one of the `postrender` actions:
```json
// job.json
{
"actions": {
"postrender": [
{
"module": "@nexrender/action-upload",
"input": "",
"provider": "s3",
"params": {
"region": "us-east-1",
"bucket": "name-of-your-bucket",
"key": "folder/output.mp4",
"acl": "public-read"
}
}
]
}
}
```
* `input` optional argument, path of the file you want to encode, can be either relative or absulte path. Defaults to current job output video file.
* `provider` required argument, object containing the name of the provider
* `params` required argument, object containing parameters for …
> Implement post-render action for uploading to an S3 bucket

- README.md
- packages/nexrender-action-upload/index.js
- packages/nexrender-action-upload/readme.md
This PR makes minor refinements to the `action-upload` module for uploading to Amazon S3.
- Round progress percentage to nearest whole number ie. 53%, 98%.
- Add reference to AWS documentation for setting credentials.
> Refinements to action-upload for S3 upload

- README.md
- packages/nexrender-core/src/tasks/render.js
PR for #167.
- Added `onRenderProgress` callback to job object
- Updated README.MD.
This is a non-breaking change.
> Add render progress callback to job object

- packages/nexrender-core/src/assets/nexrender.jsx
This bug occurs when layers or compositions are selected by name and the provided callback adds a new layer or composition. Then it happens frequently, that the selected item is selected *again* as it is moved one index up in the item list.
E.g, we had the case that calling `replaceFootage` with a file named `data_something.mp4` and adding it to `RenderComp` would add this file many times. AE would for unknown reason stop to add it after about 26 times, but on some render machines this was enough to crash rendering because of memory issues. Therefore, I would flag this bug as **serious**.
The fix will now make two separate iterations. The first will find all matching items and then a second iteration on a separate array of the found items will envoke the callback.
The bug has been fixed …
> Bug fix: unclean list iteration for selected compositions and layers 

- packages/nexrender-core/src/helpers/autofind.js
Don't know if "CC" is also removed from the Windows release.
> Fixing path for AE 2020 (MacOS)

- README.md
- packages/nexrender-core/src/tasks/download.js
Hi @inlife. I have explained the rationale for this in the commit message (also copied below). I'm not 100% sure if this is the right approach to solve the problem. If you can think of a better way, let me know and I'll rework it.
After Effects appears to rely on assets having a particular extension.
For example, to replace an image, it expects the file to have an image
file extension like `.jpg`. If you feed it an image file that does not
have such an extension, `aerender` will fail rendering.
When downloading a remote image, the nexrender downloader typically
saves it to the working directory, named with the basename of the remote
path. This change allows you to optionally specify a file extension in
the job config, which will be appended to the filename when it is
downloaded.
> Allow adding a file extension when downloading files

- packages/nexrender-provider-gs/src/index.js
The 'close' callback is not called on createWriteStream, which meant the promise was never resolved or rejected. This fix uses the 'finish' callback to both log and resolve a complete upload.
> Update GS upload to resolve promise

- packages/nexrender-core/src/tasks/render.js
Add functionality to pipe the stdout and stderr of the child_process of the binary to the `settings.logger.log`. This allows users to hook in the log stream instead of having to read a separate log file. 
Add a settings option like `verbose` to enable piping the result to the logger. 
```js
const { spawn } = require('child_process');
const { createInterface } = require('readline');
const renderer = spawn('./render.js', ...);
const reader = createInterface({ stdin: renderer.stdout, stdout: process.stdout });
reader.on('line', data => {
// .. to something with process output, like calculate progress...
});
```
1. Add `verbose` to options
```js
const { init, render } = require('@nexrender/core');
const settings = init({ logger: console, verbose: true });
return render(..., settings);
```
2. …
> Add functionality to pipe stdout/stderr to logger

- packages/nexrender-action-encode/index.js
@inlife 
Was cleaner to reopen a new pr.
Also checked about the inconsistency and it was actually my mistake, this always works on any PC I tried (both Mac an PC).
> Fix ffmpeg path for pkg

- packages/nexrender-action-encode/index.js
As mentioned in #330, it looks like the promise is resolved before the resources are freed and this may result in a EBUSY error. 
Since this exception is not handled, it resulted in an unhandled promise exception and the rendering promise is never settled. This may cause the flow to get stuck in certain implementations which rely on the previous job to be finished before listening for new jobs.
This small PR tries to fix both problems:
1. By listening to the "close" event on the WriteStream (https://nodejs.org/api/stream.html#stream_event_close) which ensures that the resources have been closed and they are now free before resolving the promise
2. Catches exceptions that may happen outside the ffmpeg instance (such as in this case the EBUSY error)
> Fix ffmpeg Error: EBUSY (action-encode module)

- packages/nexrender-core/src/tasks/script.js
- packages/nexrender-core/src/tasks/setup.js
Looks like my editor stripped a bunch of trailing/blank spaces, but actual changes are:
https://github.com/inlife/nexrender/compare/master...jasonayre:fix_script_render?expand=1#diff-4ec79c8dd953c5e8f189c82ee00f3d7aR177
**(missing arg causing script running to blow up for me)**
and: https://github.com/inlife/nexrender/compare/master...jasonayre:fix_script_render?expand=1#diff-d3e88419d375241866b441b854b4ae5cR37
**(render blows up if no postrender actions are passed to it ATM)**
-- Also was trying to figure out how to get data back as a result of running a script, don't happen to have any insight on how I could do that do you? (trying to parse the structure of the AE project in a script, and pass it back somehow - I've just returned the result of the jsx function being executed in my own …
> Fix script render

- packages/nexrender-action-encode/index.js
ffmpeg-static returns a string, there is no path property
> FIX : requiring ffmpeg-static 

- packages/nexrender-cli/src/bin.js
- packages/nexrender-core/src/index.js
- packages/nexrender-core/src/tasks/render.js
new settings.skipRender prop to allow nexrender to execute jsx scripts on .aep files without rendering an output. Useful for interrigation projects for things like default text values that can be stored and then manipulated manually for later rendering.
> Added settings.skipRender

- packages/nexrender-core/src/assets/commandLineRenderer.jsx
Using `evalFile` instead of `eval` to run scripts allows for proper script path resolution using properties like `$.fileName`
If `eval` is used, `$.fileName` will resolve to the `commandLineRenderer.jsx` path in the AE Startup folder.
> use evalFile instead of eval to run scripts in commandLineRenderer

- packages/nexrender-core/src/tasks/render.js
When using skipRender setting, aerender binary fails to run because no output argument is specified (even though it is only rendering a single frame). 
Setting output regardless parameter regardless of skipRender value fixes this issue. 
Experiencing this issue on latest version of AE CC19, this is possibly not an issue in newer version of the aerender binary.
> Set job.output when using skipRender

- packages/nexrender-core/src/tasks/download.js
The asset src uri was being encoded twice if it is already encoded, I compared it first with decoded uri to make sure it is not already encoded and if it is we take it as is.
> Make sure that asset uri is not encoded twice

- .prettierignore
- README.md
- packages/nexrender-cli/src/bin.js
- packages/nexrender-core/src/helpers/autofind.js
- packages/nexrender-core/src/helpers/path.js
- packages/nexrender-core/src/index.js
- packages/nexrender-core/src/tasks/render.js
- packages/nexrender-core/src/tasks/script.js
- packages/nexrender-core/test/manual-win-wsl.js
- packages/nexrender-core/test/mywsljob.json
Adds support for `WSL (Windows Subsystem for Linux)` and `.prettierignore`.
Currently `nexrender` does not support users who are using `WSL`. This PR adds support for these users with little change to the base code.
>Init Issue [Is it possible to run Nexrender from WSL2?](https://github.com/inlife/nexrender/issues/422)
Due to issues with my last PR I have also added in a `.prettierignore config` in order to tell prettier to not format.  
Tested on `Windows` and `WSL`.
Will need to be tested on `macOS`, though I do no believe it should have affected it.
Feedback welcomed.
> Feat: WSL Support & .prettierignore

- packages/nexrender-core/src/index.js
Current WSL detection works with a case-sensitive match on 'microsoft', which means it fails when your OS release string contains 'Microsoft' instead.
This resolves that issue.
> Improve WSL detection

- packages/nexrender-action-encode/index.js
- packages/nexrender-action-upload/index.js
- packages/nexrender-provider-s3/src/index.js
Initial PR to add the ability for action-encode and action-upload to specify and use callbacks (onProgress, onComplete). Eventually it would be good to be able to pass this back up to the api so we can report progress on other steps of the pipeline not just rendering.
eg
```javascript
postrender: [
{
module: '@nexrender/action-encode',
output: 'output.mp4',
preset: 'mp4',
onProgress: (job, value) => do something
onComplete: (job, value) => do something
}
]
```
Thoughts?
> Callbacks for action-encode and action-upload

- packages/nexrender-action-encode/index.js
This PR should fix 2 issues:
- Sometimes the line is split so the regex doesn't properly capture the totalDuration.
- I was passing the wrong variable back to the callback for onProgress
> Fixing encoding percentage

- packages/nexrender-server/README.md
- packages/nexrender-server/src/index.js
If you need to deploy `nexrender-server` behind the load balancer, then you need to define a valid health check. Health checks must usually return `200`.. 
Currently we have a problem that we want to place it behind the Kubernetes ingress with using the secret of course.. However Kubernetes still does not have a possibility to define a health check that includes a header value from secrets.. Thus we cannot set `nexrender-secret` header and create a health check (we could, but then we would expose secret in the deployment files)..
I created this small patch, that exposes `/health` which can be accessed without the `nexrender-secret` header. Simply returns 200.
Let me know if you want me to do anything else. Hope this gets in soon..
> added /health endpoint that always returns 200 without secret

- packages/nexrender-core/readme.md
I noticed a small typo in a readme, it read "Apllications" instead of "Applications".
> Fix typo (Apllications)

- packages/nexrender-action-upload/readme.md
- packages/nexrender-provider-gs/README.md
- packages/nexrender-provider-gs/src/index.js
GS offers to set a `Cache-Control` for each uploaded object. As we are uploading are videos, they are usually immutable and huge in size.. With `cacheControl` option we can set way longer cache props, thus saving on the transfer sizes, at least for the users that open the video in the browser.. I think this PR is thus valid and helpful..
I initialized the empty metadata if no optional params are passed, I guess this should be fine..
Let me know if anything should be improved..
> add the cacheControl meta-data in the gs provder

- packages/nexrender-action-copy/index.js
- packages/nexrender-action-encode/index.js
- packages/nexrender-server/src/helpers/database.js
- packages/nexrender-server/src/routes/jobs-create.js
- packages/nexrender-server/src/routes/jobs-pickup.js
- packages/nexrender-types/job.js
- packages/nexrender-worker/src/index.js
Adds a few fields to entry items on the database:
* createdAt (already existed but wasnt being populated correctly)
* startedAt: the time the worker started picked the job up for rendering
* finishedAt: the time the worker finished processing
* errorAt: time at which the worker encountered an error processing
* jobCreator: remote ip address that submitted the job
* jobExecutor: remote ip address of the worker that picked up the job for processing
Also adds a few QOL:
* print ffmpeg command when --debug flag is set
* fix checking if output is a directory (checking names is unreliable)
> Add stats about rendering times

- packages/nexrender-cli/src/bin.js
Hi Vladyslav,
this is just a one line improvement but one that has helped us a lot.
The nexrender-cli does not have an argument to turn verbose output on.
But it has the `--debug` option and this change makes that option turn on verbosity as well.
I guess that this is a sensible choice since you will want to see the verbose output when debugging anyway.
Kind regards
Bernd
> debug should imply verbosity

- README.md
- packages/nexrender-action-encode/index.js
This allow for creating more files with known names such as encoding in multiple bitrates for hls streams
such as
```
{
"module": "@nexrender/action-encode",
"output": "encoded_playlist_%v.m3u8",
"params": {
"-acodec": "aac",
"-vcodec": "libx264",
"-pix_fmt": "yuv420p",
"-map": [
"0:0",
"0:0",
"0:0"
],
"-b:v:0": "2000k",
"-b:v:1": "1000k",
"-b:v:2": "500k",
"-f": "hls",
"-hls_time": "5",
"-hls_list_size": "0",
"-var_stream_map": "v:0,name:high v:1,name:medium v:2,name:low",
"-master_pl_name": "master.m3u8",
"-hls_segment_filename": "${workPath}\\encoded%d_%v.ts",
"-s": "540x960"
}
}
```
> Creates a simple text mask for the current workPath for action-encode

- packages/nexrender-core/src/tasks/download.js
`path.extname` returns the extension including the period symbol, or an empty string when no extension is present. Currently this code leads to names like `abc123..aepx` being generated.
https://nodejs.org/api/path.html#path_path_extname_path
This change just removes the extra period from the constructed string.
> Bug fix: Remove extra period from randomly generated name

- packages/nexrender-provider-s3/readme.md
- packages/nexrender-provider-s3/src/index.js
For use-cases where you're downloading or uploading from buckets in different S3 (or other provider) accounts, it's currently difficult to rely on the current S3 provider implementation.
This update adds the option to:
- Specify an AWS credentials profile in params (see [SharedIniFileCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html)
- Specify an access key ID and secret access key in params
- Specify a profile in environment variables (AWS_PROFILE)
It resolves credentials in the following order:
- Profile specified in params, if not specified then
- Access key ID and secret access key in params, if not specified then
- Profile specified in environment variables, if not specified then
- Access key ID and secret access key in params, if not …
> Feature: add more credential config options to S3 provider

- packages/nexrender-provider-s3/src/index.js
Whoops, forgot to commit local change, should actually get credentials from the credentials object and not top level params :)
> Bug fix: pull S3 credentials from correct place

- README.md
CreateVid.io is now publicly available (and working) to help kickstart dynamic video rendering projects. It includes a frontend to queue, render and store videos in the cloud. We are adding new features but looking for help from the community.
> Add CreateVid repo

- packages/nexrender-action-encode/index.js
This is a simple fix for an issue I've been having for a while. It casts the variable value to a string so the .replace method works, otherwise it throws a nasty error.
I edited this file manually a couple months ago in production, and so far it has been fine, and I doubt it should break anything as the replace method only works on strings either way.
> Cast value to string so .replace works

- packages/nexrender-core/package.json
- packages/nexrender-core/src/tasks/download.js
As the title says, if the asset file extension is not present, now it's being appended based on response header content-type for `http` and `https` protocols.
> Append file extension based on content-type

- package-lock.json
- packages/nexrender-server/README.md
- packages/nexrender-server/src/routes/jobs-pickup.js
- packages/nexrender-types/job.js
Allows you to supply a numerical "priority" field for each job and the workers will then pick up the ones with the highest priority, and if there's a collision it will choose the oldest one automatically.
> Job priority

- packages/nexrender-core/src/tasks/download.js
**Problem:**
My static assets was like 
```
{
name:"example.jpg",
type:"static",
src:"https://example.com/example.jpg"
}, 
```
it gives download file as **example.jpg.jpg** as it appends the extension in **asset.dest**,
line 34 forces **destName=example.jpg** and then **assets.desc=workpath+"/"+example.jpg**, then after download  it satisfies line 74  as extension key is not there in static assets, 
**Solution:**
**it restricting now to do this by checking the extension presence in asset.dest so not to repeat like workpath+example.jpg (from asset.dest)+".jpg" (from content type) which gives /example.jpg.jpg**"
> Fix for downloading static assets

- packages/nexrender-action-encode/index.js
- packages/nexrender-core/src/tasks/render.js
In some instances (like running nexrender-workers with pm2), a command prompt (`cmd.exe`) window would pop-up every time an external process was spawned (like `aerender` or `ffmpeg`).
To, workaround this problem (which can be quite annoying), I've added the `windowsHide` parameter to all the `spawn` calls. This will:
> Hide the subprocess console window that would normally be created on Windows systems
([Source](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options))
Related: Unitech/pm2#2182
> fix: prevent command prompts pop-ups in Windows

- packages/nexrender-provider-s3/package.json
This fixes the NoSuchKey error that happens when URLs ending with a query string are parsed.
> update amazon-s3-uri package to 0.1.1 in s3 provider

- README.md
I've created https://github.com/dylangarcia/nexrender-action-unzip to help aid in workflows that require a full project to be downloaded and extracted before rendering.
> Add nexrender-action-unzip to external packages

- README.md
- packages/nexrender-core/src/tasks/render.js
The callback would send captured error message from the processed log file.
At the moment it seems it can be an open selection of text, plausible even multiple lines of text. A future improvement would be to standardize the possible errors but need to observe first. In any way, this allows to feed back a more precise error message that is enough to diagnose the reason why the job failed.
Currently and after this change, the job would still hard-fail at output file not found. It is up to SDK user to act upon callback.
---
Testing:
1. Run regular job (that would fail), there must be new log line that starts  with `[uid] rendering reached an error: ...`
2. Register a callback event on the job - it would receive the same message in the second parameter
> Add onRenderError callback event

- README.md
- packages/nexrender-core/src/assets/nexrender.jsx
I made a few small changes to `selectCompositionsByName()` function in `nexrender.jsx` that enables searching nested compositions. Nested compositions must be specified in a job json like this: `"Parent Comp->Child Comp->Grandchild Comp"`. 
For example
```json
{
"type": "data",
"composition": "FULL_HD->intro->logo comp",
"layerName": "logo",
"property": "Transform.Position",
"value": [100, 150]
}
```
Note, that you have to specify the child composition name, not a layer name.
The regular composition names, as well as `*` still work.
> Added nested comps to nexrender.jsx

- README.md
I see there is already another package on the same topic, but this has a different approach that tackles following issues:
1st: the structure of files within the ZIP might differ from one to another - a user could zip files in the root or a directory within the zip or whatever (users can be messy)
2nd: the name of `.aep` file is not known and in fact, is not important - the ZIP templates are being worked by the `.zip` basename.
> Added external link to nexrender-action-template-unzip

- packages/nexrender-core/src/helpers/autofind.js
#651 was good but didn't quite cover all the possibilities for the Adobe After Effects 2022 path on Mac. This adds in an additional matching string for completeness.
> Add additional AE 2022 autofind string match for Mac

- packages/nexrender-core/readme.md
- packages/nexrender-core/src/tasks/actions.js
- packages/nexrender-worker/readme.md
Resolves #671
Also updated the readme files to include the new `actions` field. Implementation should be fully backwards compatible. 
If an action is both defined in the `actions` object and installed as a package (or there is a name collision) the function in the `actions` object takes precedence.
> Enable action functions to be passed directly in actions key in settings

- packages/nexrender-server/package-lock.json
- packages/nexrender-server/package.json
- packages/nexrender-server/src/routes/jobs-pickup.js
Resolves #670
Ensures that the jobs picked up by the workers will always be unique.
I didn't add a timeout to the mutex lock as I think the way it's currently used shouldn't cause a stale mutex to ever occur but including it isn't too difficult either, just figuring out the right amount of time for the timeout is a bit tricky. I would recommend leaving this as is for now and I'm happy to add the timeout if it turns out stale mutex is a possibility in this case.
> Add mutex lock to server pickup route

- packages/nexrender-types/job.js
- packages/nexrender-types/package.json
We are flagging the `nanoid` package as a security concern internally. Here is a PR that would resolve it. I have no idea if it's typical to submit a PR for a package dependency to fix a security vulnerability. Please let me know if you don't handle security vulnerabilities this way.
https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
> install latest nanoid package

- packages/nexrender-action-upload/package.json
this is #707 bug patch
@nexrender/action-copy depends on @nexrender/provider-sftp@^1.37.10 which is not exists
> fix @nexrender/action-upload dependency of @nexredner/provider-sftp

- packages/nexrender-action-cache/index.js
- packages/nexrender-action-cache/readme.md
Adds a time-to-live (in ms) functionality to the cache action.
Use case:
We use S3 to store our templates, sometimes we change them, and we don't want to have to rename them. Instead, we'd like to add a time-to-live on the template, and delete it incase that time has expired
> add ttl on action cache

- package-lock.json
I would like to help contribute by taking a look at some of the security issues with this repo (a check with `npm audit` states there are currently 46 vulnerabilities). In order to do this, npm v8 informs me the lockfile needs to be upgraded to version 2 - this PR does that and only that (no change to any existing packages)
> Upgrade NPM lockfile version to 2

- packages/nexrender-worker/src/bin.js
It's impossible to disable "stop-on-error" since it was typed Boolean.
This condition allows it to be set to false if it's filled in with the worker.
> set stop-on-error to false

- packages/nexrender-provider-s3/src/index.js
- packages/nexrender-provider-s3/src/uri.js
Implemented a light `amazon-s3-uri` version to allow file downloads from  digitaloceanspaces, used only when needed.
> Allow download from digitaloceanspaces in provider s3

- packages/nexrender-api/src/job.js
Resolves #752 
In addition to deprecating `getJob()`, using deprecated functions such as `getJob()` or `removejob()` will not print a deprecation warning message.
Also implemented `fetchJob()` (which I wanted to name `getJob()` originally) that similar to `listJob()` but only return one job object and not in an array.
> Deprecate getJob() and implement fetchJob()

- packages/nexrender-core/src/helpers/autofind.js
Hi, we're using nexrender with a fresh new installation of AE and the executable was not found, as the new installation path `C:\\Program Files\\Adobe\\Adobe After Effects 2023\\Support Files` is not managed by the autofind helper.
The PR extends defaults paths to handle new "2023" paths.
> adding support for finding aerender.exe in adobe after effects 2023

- packages/nexrender-core/src/tasks/cleanup.js
In task cleanup use`path.join` to make it works also on windows.
> Use path join in task cleanup

- packages/nexrender-core/src/tasks/render.js
AE2023 seems to use `.mp4` as default file format for result.
> Task render looking for also mp4 files for AE 2023

- packages/nexrender-worker/src/index.js
an error message object cannot to convert to string by using stringify. it will return an empty object ``{}``
Before:
After this fix:
> Fix error message object to string on worker

- README.md
- packages/nexrender-api/src/job.js
- packages/nexrender-server/README.md
- packages/nexrender-server/src/helpers/functions.js
- packages/nexrender-server/src/index.js
- packages/nexrender-server/src/routes/jobs-create.js
- packages/nexrender-server/src/routes/jobs-pickup.js
- packages/nexrender-types/job.js
- packages/nexrender-worker/readme.md
- packages/nexrender-worker/src/bin.js
- packages/nexrender-worker/src/index.js
Hi @inlife 
I'm adding a tag selector option on the worker, so the worker can pickup a job with specific tags.
For example.
If i create these job on the server
> ![image](https://user-images.githubusercontent.com/3202529/203948712-b8346c3a-b590-43b9-93fb-3f8765614eb3.png)
> ![image](https://user-images.githubusercontent.com/3202529/203948983-2c10a68b-5b11-47a7-aca8-d263fb54cbb0.png)
> ![image](https://user-images.githubusercontent.com/3202529/203949158-5a8b0a0c-fe17-464c-aa5b-21e95556ecd8.png)
> ![image](https://user-images.githubusercontent.com/3202529/203949266-2ea6b70a-6264-48ec-bb02-cf31692861be.png)
Explanation:  _Worker 1_ can only pick up _Job 1_ because only _Job 1_ meet the criteria (by tags).  However, _Worker 2_ can pick up _Job 1_ or _Job 2_ or any other Jobs on the server. …
> Feature: tag selector, worker to pickup job wiith specific tags

- packages/nexrender-core/src/helpers/autofind.js
I noticed After Effects 2023 (without CC) was missing from autofind.js. This PR adds this version for Darwin
> Update autofind.js to include After Effects 2023 for MacOS

- packages/nexrender-api/readme.md
- packages/nexrender-api/src/index.js
- packages/nexrender-worker/readme.md
- packages/nexrender-worker/src/bin.js
- packages/nexrender-worker/src/index.js
Resolves #821
Additional object property can be passed to the API's `createClient` argument to define custom header to use and the same is also enabled for the worker as an extra optional argument to the `start` function as well as command line argument.
Documentation are included and implementation tested on a custom setup I have. 
With the programmatic API, it is possible to define headers with functions that will be evaluated to a header value upon each request performed by the client. I would consider this advanced usage that provide lots of flexibility but shouldn't be used unless the function's implementation is sound and performant (see documentation for a bit more note).
> Implement custom headers for use with API client

- packages/nexrender-action-cache/index.js
- packages/nexrender-action-cache/readme.md
- packages/nexrender-action-cache/test/manual.js
Addresses #834 (Don't want to close the original issue yet)
Implemented assets caching with `nexrender-action-cache` and by providing the extra boolean `cacheAssets` option to the action definition assets as well as job template will be cached locally. One of the reason this is optional is because if more than one assets have the same name, they will overwrite each other in the cache directory. It could be possible to use the full URL as the filename to prevent unintended overwriting but it is complicated in other ways. 
As such I'm not entirely satisfied with this implementation but I don't think it is possible to build out what I'd prefer with `nexrender-action-cache` while preserving backwards compatibility. So I'm going to leave `nexrender-action-cache` at this point and build out …
> Include assets to be cached by nexrender-action-cache

- README.md
- packages/nexrender-cli/src/bin.js
- packages/nexrender-core/package.json
- packages/nexrender-core/readme.md
- packages/nexrender-core/src/tasks/download.js
- packages/nexrender-worker/readme.md
- packages/nexrender-worker/src/bin.js
Resolves #834
Implement HTTP caching support for assets and project files using make-fetch-happen. Server will need to implement the relevant headers and handle relevant requests appropriately for it to work fully (since the server is the one that actually knows if a file has changed or not).
I've not fully tested this as I don't have a working rendering environment at the moment, so it may be good to test this out first to ensure I didn't get anything wrong.
> HTTP caching

- packages/nexrender-core/src/assets/commandLineRenderer-2022.jsx
Did a diff to solve another problem and found this little bugfix. 
Very relevant for the new -renderSettings and -outputSettings flags, as it trims whitespace which allows for greater tolerance for the parameter strings.
> Fix to trim(s) in commandLineRenderer from 2023

- packages/nexrender-action-encode/index.js
Gifs won't output in most cases because of extraneous ffmpeg arguments that trim the clip. This removes them
> fix: Gif output

- packages/nexrender-worker/readme.md
- packages/nexrender-worker/src/index.js
I've added Callback like onFinished and onError.
The current implement onRenderingProgress won't be called if the project has been finished, so onFinished can be helpful there.
onRenderError only throws the error regarding rendering, the  onError functions throws all other errors.
> Added onFinish and onError

- packages/nexrender-cli/src/bin.js
I have a use case to know whether a job has failed or not based on the exit code of nexrender. It's pretty standard for a CLI to return an error code of non-zero for a failure.
> exit with exit code 1 on aerender failure for CLI

- packages/nexrender-core/src/tasks/render.js
This fixes a regression introduced in the PR #656 two years ago, it causes invalid argument `-mfr` error when trying to render with aerender version older than 2022.
In #656 @chrisapplegate added new `commandLineRenderer-2022.jsx` for AE 2022+, and kept `commandLineRenderer-default.jsx` for pre-2022, they were patched correctly. But Chris forgot to check the version and applied the cc2022-only argument `-mfr` in all cases, resulting a regression.
It seems this regression has lasted a long time and no one noticed. Recently I tried to upgrade the dependencies of my project which stays at using old version of aerender and found that a `-mfr` error throws when I update `@nexrender/core` to any version greater then 1.32.x. #656 was shipped in 1.33.0, all versions of `@nexrender/core` starting …
> fix(core): use `-mfr` only for cc2022+

- packages/nexrender-cli/src/bin.js
usage: ./nexrender-cli-macos -c
error: 
pkg/prelude/bootstrap.js:1926
return wrapper.apply(this.exports, args);
^
ReferenceError: init is not defined
at Object.<anonymous> (/snapshot/nexrender/packages/nexrender-cli/src/bin.js)
at Module._compile (pkg/prelude/bootstrap.js:1926:22)
at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:834:12)
at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
at node:internal/main/run_main_module:17:47
Node.js v18.5.0
> fixbug ReferenceError: init is not defined

- .github/stale.yml
It's my impression that generally the label wontfix is used on github for issues where the maintainer has actively decided that an issue should not be fixed, and not simply for an issue that has not received attention. This is a bit confusing when looking at issues in the nexrender repo and I propose to change it to apply the label stale.
Issues with the label wontfix will deter contributors from working on them.
> Use the label Stale for stale issues instead of wontfix

- packages/nexrender-core/src/tasks/script.js
Seems this method is written with the expectation that matchAll (https://github.com/IonicaBizau/match-all/) is returning a nested array with capture groups. Maybe it has done before? Atleast it doesn't now. Using the native string.matchAll makes the remaining method work as expected printing warnings for the appropriate parameters that are accessed with NX.get but does not have values defined in the job. 
Not sure if there are other places where the use of the matchAll package may be causing similar issues - did not test with anything else than parameters.
I could make a PR to replace all uses of match-all with native string.matchAll unless you are aware of some edge cases where the library is solving some issue - may be on certain platforms?
> Solve issue with EnhancedScript.prototype.findMissingMatchesInJSX only reporting parameter 't' as missing. Fixes #716

- packages/nexrender-core/src/helpers/autofind.js
```
Error: you should provide a proper path to After Effects' "aerender" binary
at init (/snapshot/nexrender/packages/nexrender-core/src/index.js)
at start (/snapshot/nexrender/packages/nexrender-worker/src/index.js)
at Object.<anonymous> (/snapshot/nexrender/packages/nexrender-worker/src/bin.js)
at Module._compile (pkg/prelude/bootstrap.js:1926:22)
at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:834:12)
at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
at node:internal/main/run_main_module:17:47
```
I've added 'After Effects 2024' to darwin.
When start nexrender on MacOS, an error message appears.
I noticed that 'After Effects 2024' is missing from the …
> Fix missing path for MacOS After Effects 2024 in autofind.js

- packages/nexrender-action-encode/index.js
- packages/nexrender-action-encode/readme.md
The problem this pull request solves is when you input a valueless param in job settings (for example `-an`). I've tried empty string which results with a double space in the final command.
The rest is explained in the readme change and comments
> Fix | nexrender-action-encode | valueless ffmpeg params

- packages/nexrender-core/src/tasks/render.js
- packages/nexrender-core/src/tasks/setup.js
When rendering TIF images, there was a problem with locating the final file. Since TIF generates file sequences, there were issues with file naming, and the render would fail. Now, everything looks great
> added tif support for render image sequences

- packages/nexrender-core/src/tasks/download.js
The error handling in the file downloading task of nexrender-core has been refactored. Instead of rejecting with an object containing a complex error message and metadata, a simple error message in string format is now used, allowing nexrender-worker to log asset download errors.
> Refactor error handling in file download task

- packages/nexrender-core/src/tasks/download.js
Always randomize filenames for parallel downloads.
Fixes #1003
> Resolve issue https://github.com/inlife/nexrender/issues/1003

- packages/nexrender-core/src/tasks/script/wrap-footage.js
As described in this issue https://github.com/inlife/nexrender/issues/1008
> If an asset of the project has an apostrophe in the path then the generated nexrender-script is faulty, raising an error "SyntaxError: Expected: )"
> 
> **Information about environment** Version of nexrender-worker-win.exe: 1.50.7 Version of nexrender-server-linux: 1.49.3 Both of them are precompiled versions from the download page
> 
> The workers are running on Windows 11 Pro The server is running on a Debian
> 
> After cloning the repository I could find the issue on [line 9 of the file packages/nexrender-core/src/tasks/script/wrap-footage.js](https://github.com/inlife/nexrender/blob/63c93f142f3f30916dd2817a0e83bfad1d9d94b3/packages/nexrender-core/src/tasks/script/wrap-footage.js#L9) which doesn't escape them. …
> add apostrophe escapement to wrapFootage

- packages/nexrender-worker/src/bin.js
- packages/nexrender-worker/src/instance.js
This PR introduces two new arguments to the command line interface for nexrender-worker:
--stop-at-time: This parameter allows users to specify a certain local time when the worker will terminate. An example usage would be --stop-at-time=5:00, which will stop the worker at 5 am local time.
--stop-days: This parameter works in conjunction with the --stop-at-time parameter and allows to specify on which weekdays the worker should terminate. The days are represented as numbers where 0 is Sunday and 6 is Saturday. For instance, --stop-days=1,2,3,4,5 will stop the worker at the specified time from Monday through Friday.
This enhancement increases the flexibility of controlling worker runtime and can help schedule tasks more effectively.
Example use:
```nexrender-worker-win64.exe …
```
> Added --stop-at-time and --stop-days arguments

- packages/nexrender-core/src/tasks/render.js
- packages/nexrender-worker/src/bin.js
This pull request introduces a new feature that adds language support for rendering errors and progress logs in After Effects.
The changes allow users to specify the language of their After Effects installation via a new --language flag. This flag directly impacts the parsing of error and progress messages from the renderer. Syntax and text from these logs can fluctuate based on the language, thus this feature enhances the versatility and compatibility of our tool across multiple language installations.
Changes:
----------
- Introduced a new --language flag to specify the language of After Effects installation.
- Added support for interpretation of error and progress logs in both English and German.
- Created a translation map to easily handle translation of keywords and phrases present …
> Add language support for rendering errors and progress logs

- packages/nexrender-action-cache/index.js
packages/nexrender-core/src/tasks/download.js will randomize the download destination.
packages/nexrender-action-cache/index.js is still looking for the filename provided as source and will crash if you try caching the template file.
This patch fixes the issue by using the assets dest property if provided.
> Fix asset source path handling in cache action

- packages/nexrender-database-redis/readme.md
- packages/nexrender-database-redis/src/index.js
Introduced the `SCAN_CHUNK_SIZE` environment variable to customize the number of keys retrieved per `SCAN` operation, with a default value of 10. Updated the logic in `index.js` to utilize this variable and documented the change in the README. This enhancement allows for greater flexibility and performance tuning based on specific use cases.
> Add configurable SCAN_CHUNK_SIZE for Redis database queries

- packages/nexrender-core/src/helpers/autofind.js
MacOS/Darwin AE installations can be under either of these paths
- `/Applications/Adobe After Effects 20XX/`
- `/Applications/Adobe After Effects CC 20XX/`
This covers both options
> Add additional macOS 2025 AE binary path for autofind

- packages/nexrender-action-fonts/index.js
this small code change should prevent .otf font files from being discarded/ignored when auto installing fonts by the fonts-action
> small fix to provide otf font support in the automatic font installer
